repos:{% if cookiecutter.use_strict_typing == 'y' %}
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        name: Static type checks (mypy)
        exclude: "docs"
        additional_dependencies: [types-setuptools]{% endif %}

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.1
    hooks:
      - id: ruff
        name: Lint with Ruff
        args: [ --fix ]
        types_or: [python, pyi, jupyter]
      - id: ruff-format
        name: Format with Ruff
        types_or: [python, pyi, jupyter]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        name: Check for added large files
        entry: check-added-large-files
      - id: check-json
        name: Check JSON
        entry: check-json
        types: [json]
      - id: check-toml
        name: Check Toml
        entry: check-toml
        types: [toml]
      - id: check-yaml
        name: Check Yaml
        entry: check-yaml
        types: [yaml]
      - id: end-of-file-fixer
        name: Fix End of Files
        entry: end-of-file-fixer
        types: [text]
        stages: [commit, push, manual]
      - id: trailing-whitespace
        name: Trim Trailing Whitespace
        entry: trailing-whitespace-fixer
        types: [text]
        stages: [commit, push, manual]
      - id: debug-statements
        name: Check for debug statements
