image: ubuntu:latest

pipelines:
  branches:
    '{master,feature/ci}':
      - step:
          name: build and test
          caches:
            - pip
          script: # Modify the commands below to build your repository.
            - DEBIAN_FRONTEND=noninteractive apt-get update --fix-missing
            - DEBIAN_FRONTEND=noninteractive apt-get install -y python3-dev python3-venv make
            - python3 -m venv --system-site-packages py38-venv
            - . py38-venv/bin/activate
            - make install-dev
            - make test
