[tool.ruff]
line-length = 120
target-version = "py310"

[tool.ruff.format]
quote-style = "single"
docstring-code-format = true

[tool.docformatter]
wrap-summaries = 120
wrap-descriptions = 120
in-place = true
recursive = true

[tool.bumpver]
current_version = "{{ cookiecutter.version }}"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = false

[tool.bumpver.file_patterns]
"setup.py" = [
    "{version}",
]
"{{ cookiecutter.project_slug }}/__init__.py" = [
    "__version__ = '{version}'",
]
