name: Run code checks for PRs

on:
  pull_request:
    branches: [master, test, prod]

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  lint:
    name: Run linting and formatting checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install package
        shell: bash -el {0}
        run: pip install-dev

      - name: Run linting and code format checking with Ruff
        shell: bash -el {0}
        run: make lint
